version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  fastapi:
    build: .
    container_name: fastapi-app
    depends_on:
      - mongodb
    ports:
      - "8000:8000"

volumes:
  mongodb_data: